### ISSUE TITLE
Indigo release

### ISSUE THREAD

**Issue by roehling** [ros-drivers/prosilica_driver#8]
I am currently working on migrating our software to ROS Indigo and found these packages missing. Will they be released for Indigo?

**Comment by wjwwood** [comment]
As far as I know, there is nothing preventing the release.

**Comment by wjwwood** [comment]
I could do the release if @trainman419 doesn't have time.

**Comment by trainman419** [comment]
I'll take care of this. I need to revert or hide the changes in c232a54e47cfca358bc74b85bcaaa27617926842 before I do a new release, because they're not yet compatible with rqt_reconfigure.

**Comment by trainman419** [comment]
I've rolled back the reconfigure groups and released the resulting version as 1.9.4 into Hydro ( https://github.com/ros/rosdistro/pull/5137 ) and Indigo ( https://github.com/ros/rosdistro/pull/5140 )
